
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 15 19:35:06 CEST 2007
//----------------------------------------------------

package nnsec.parser;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int GROUP_ID = 13;
  public static final int LINK_WEIGHT = 20;
  public static final int LINK_OUTPUT_NODE_ID = 19;
  public static final int DESC = 4;
  public static final int THRESHOLD_VALUE = 16;
  public static final int NET_SEC = 2;
  public static final int O_NODE_SEC = 9;
  public static final int I_NODE_SEC = 7;
  public static final int NODE_ID_VALUE = 21;
  public static final int NAME = 3;
  public static final int ACTVF = 5;
  public static final int LINK_INPUT_NODE_ID = 18;
  public static final int STRING = 24;
  public static final int WEIGHT_VALUE = 22;
  public static final int EOF = 0;
  public static final int LINK_SEC = 10;
  public static final int NODE_SEC_END = 17;
  public static final int END_TERM = 25;
  public static final int LINK_SEC_END = 23;
  public static final int NODE_ID = 12;
  public static final int error = 1;
  public static final int H_NODE_SEC = 8;
  public static final int OUTF = 6;
  public static final int THRESHOLD = 14;
  public static final int ID_VALUE = 15;
  public static final int NET_SEC_END = 11;
}

